parameters:
#    bunga_front.example.class: Bunga\FrontBundle\Example

services:
#    bunga_front.example:
#        class: %bunga_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
